version: 0.2

phases:
  build:
    commands:
      - echo Build Starting on `date`
      - sudo chmod +x ./gradlew
      - sudo ./gradlew build
  post_build:
    commands:
      - echo $(basename ./build/libs/*.jar)
      - pwd

artifacts:
  files:
    - appspec.yml
    - build/libs/*.jar
  discard-paths: yes

cache:
  paths:
    - '/root/.gradle/caches/**/*'
